<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise</title>
</head>

<body>
  <script>
    //Promise/A+的3中规范中的三种状态
    const PENDING = 'pending'
    const FULFILLED = 'fulfilled'
    const REJECTED = 'rejected'
    class MyPromise {
      constructor(executor) {
        this._status = PENDING //promise的初始状态
        this._value = undefined //存储then回调的返回值
        this._resolveQueue = [] //成功函数的回调队列
        this._rejectQueue = [] //失败函数的回调队列

        let _resolve = val => {
          const run = () => {
            //对应规范中状态只能从pending转为fulfilled或者rejected
            if (this._status !== PENDING) return;
            this._status = FULFILLED //变更状态

            //从成功队列里取出回调依次执行
            while (this._resolveQueue.length) {
              const callback = this._resolveQueue.shift()
              callback(val)
            }
          }
          setTimeout(run)
        }
        let _reject = val => {
          const run = () => {
            if (this._status !== PENDING) return;
            this._status = REJECTED;
            //从失败队列里取出回调依次执行
            while (this._rejectQueue.length) {
              const callback = this._rejectQueue.shift()
              callback(val)
            }
          }
          setTimeout(run)
        }
        // new Promise()时立即执行excutor,并传入resolve reject
        executor(_resolve, _reject)

      }
      //then方法接受一个成功的回调和一个失败的回调,并push进相应的队列
      then(resolveFn, rejectFn) {
        //根据规范如果then方法的参数不是函数,我们就要忽略它,让链式调用继续往下执行
        typeof resolveFn !== 'function' ? resolveFn = value => value : null
        typeof rejectFn !== 'function' ? rejectFn = reason => {
          throw new Error(reason instanceof Error ? reason.message : reason)
        } : null
        return new MyPromise((resolve, reject) => {
          //把resolveFn重新包装一下,在push进resolve的执行队列,这是为了能够获取回调的返回值进行分类讨论
          const fulfilledFn = value => {
            try {
              let x = resolveFn(value)
              x instanceof MyPromise ? x.then(resolve, reject) : resolve(x)
            } catch (error) {
              reject(error)
            }
          }

          const rejectedFn = error => {
            try {
              let x = rejectFn(error)
              x instanceof MyPromise ? x.then(resolve, reject) : resolve(x)
            } catch (error) {
              reject(error)
            }
          }

          switch (this._status) {
            case PENDING:
              this._resolveQueue.push(fulfilledFn)
              this._rejectQueue.push(rejectedFn)
              break;
              //当状态变为fulfilled/rejected时,直接执行then回调
            case FULFILLED:
              fulfilledFn(this._value) // this._value是上一个then回调return的值(见完整版代码)
              break;
            case REJECTED:
              rejectFn(this._value)
              break;
          }
        })

      }
    }
  </script>
  <script>
    // const p1 = new MyPromise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve('result')
    //   }, 1000);
    // })
    // p1.then(res => console.log(res), err => console.log(err))
    //一秒后输出result


    const p1 = new MyPromise((resolve, reject) => {
      // setTimeout(() => {
      //   resolve(1)
      // }, 500);
      resolve(1)
    })

    p1
      .then(res => {
        console.log(res)
        return 2 //链式调用测试
      })
      .then() //值穿透测试
      .then(res => {
        console.log(res)
        return new MyPromise((resolve, reject) => {
          resolve(3) //返回Promise测试
        })
      })
      .then(res => {
        console.log(res)
        throw new Error('reject测试') //reject测试
      })
      .then(() => {}, err => {
        console.log(err)
      })

    //输出 1 2 3


    // 输出
    // 1
    // 2
    // 3
    // Error: reject测试
  </script>

</body>

</html>